--
-- create the SystemStat record if not already exists. 
--
INSERT INTO SYSTEM_STAT_T(ID, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE) SELECT 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP
	WHERE NOT EXISTS(SELECT 1 FROM SYSTEM_STAT_T WHERE ID = 1); 